apiVersion: apps/v1
kind: Deployment
metadata:
  name: machineinfo-deploymentv1
  labels:
    app: machineinfo-app
    version: v1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: machineinfo-app
        version: v1
    spec:
      containers:
        - name: machineinfo-containerv1
          image: nehashirsat/devops_repo:v1.1.0
          ports:
            - containerPort: 9000
			
---		
apiVersion: v1
kind: Service
metadata:
  name: machineinfo-service-v1
spec:
  selector:
    app: machineinfo-app
    version: v1
  ports:
  - protocol: TCP
    port: 9000
    targetPort: 9000
