apiVersion: split.smi-spec.io/v1alpha1
kind: TrafficSplit
metadata:
  name: machineinfo-service-rollout
spec:
  service: machineinfo-service
  backends:
  - service: machineinfo-service-v1
    weight: 50
  - service: machineinfo-service-v2
    weight: 50
